### ISSUE TITLE
add tests for all file types

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#11]
Create a tests file that expand the tests run on PNAD for all datasets

There should be a downlaod loop 

And an "import loop". 
Import loop should actually be two nested loops, one for each year and dataset. . 

each iteration should record the time it takes, number of observations of the improted file and number of columns of the imported file. 

The test shold be run twice, one from the local PC and one from the powerfull server. 

In the server tests, it would be usefull to keep the imported datasets of each iteration to a list (or two nested list as in the case of the dictionaries) so they can be used to test compatibility of the files over time.

**Comment by nicolassoarespinto** [comment]
Implemented in #19 . The "import loop" is the function test_read() and the "download loop" is the function test_download. The results are in  testes/Download and testes/Import.

**Comment by lucasmation** [comment]
tks
