### ISSUE TITLE
add PNS 2013 - Pesquisa Nacional de Saude

### ISSUE THREAD

**Issue by rafapereirabr** [lucasmation/microdadosBrasil#119]
Hi guys, 

IBGE have recently pusblished what is supposed to be the last version of the PNS 2013 microdata. It would be great if you could include this dataset into the package.
[ftp://ftp.ibge.gov.br/PNS/2013](ftp://ftp.ibge.gov.br/PNS/2013)

This is how I read the data using `readr`
````
    sas_file <- "./data/PNS2013/input_DOMPNS2013.sas" #SAS instructions
    sas_file <- parse.SAScii(sas_file)
    datafile <- "./data/PNS2013/DOMPNS2013.txt"
  

    # Read the .txt file
      pns2013dom <-   read_fwf(datafile,
                               fwf_widths(dput(sas_file$width),
                                          col_names=(dput(sas_file$varname))),
                               progress = interactive())
`````

**Comment by lucasmation** [comment]
done in #115, 

abraço!

**Comment by rafapereirabr** [comment]
The package returns an error when I try to `read_PNS`

```
df <- read_PNS("domicilios",i = 2013, root_path = path.expand("~/data/PNS2013"))
>Error: could not find function "read_PNS"
```

**Comment by lucasmation** [comment]
Did you reaload (remove, reinstall) the package?
I see the function here

2017-01-14 11:21 GMT-02:00 Rafael H M Pereira <notifications@github.com>:

**Comment by rafapereirabr** [comment]
It worked here, but only when I downloaded the data to the root folder. It throws and error if I try to save the data to a subfolder or if I try to read the data from another folder where I had already stored the data before.

I've tried both:
```
 download_sourceData("PNS", 2013, unzip = T, dest="./data")

 download_sourceData("PNS", 2013, unzip = T, root_path ="./data")
```

**Comment by nicolassoarespinto** [comment]
@rafapereirabr could you paste here the error you get?

**Comment by rafapereirabr** [comment]
I've pasted below the error I get when I point R to a read the data I had previously downloaded. The folders with data have exactly the same structure.. 

In any case, this is not a big issue and I wouldn't bother about this, to be honest. This can easily be solved if one downloads the data using the `download_sourceData{microdadosBrasil}` function, which should be the one's first choice if he/she wants to make the most of the package functionalities anyway.

```
pns2013dom <- read_PNS("domicilios", i = 2013, root_path = "C:/Users/rafa/Desktop/PNS2013")
> You have specified the 'root_path' argument, in this case we will assume that data is in the directory > > > specified and it is exactly as it have been downloaded from the source.
> 
> [1] "DOMPNS2013.txt"
> [1] "C:/Users/rafa/Desktop/PNS2013/pns_2013_microdados_2016_12_02/Dados"
> character(0)
> Error in read_data(dataset = "PNS", ft, i, root_path = root_path, file = file,  : 
 >  Data not found. Check if you have unziped the data
```

**Comment by nicolassoarespinto** [comment]
@rafapereirabr  There is probably some change in the structure. The path and filename that the function prints on the screen are the ones that the package searched for the data. So you can compare them with your actual folder structure to see if there is any change.

**Comment by nicolassoarespinto** [comment]
@rafapereirabr  You can just try: 

`dir("C:/Users/rafa/Desktop/PNS2013/pns_2013_microdados_2016_12_02/Dados")`

If it returns the data file your folder structure is really the same as the source and there is a problem in the package.
