### ISSUE TITLE
Dados do Censo Agropecuário

### ISSUE THREAD

**Issue by tomasbarcellos** [lucasmation/microdadosBrasil#120]
Antes de mais nada gostaria de agradecer pelo ótimo trabalho que vêm fazendo até aqui. Parabéns e obrigado por compartilhar.

Há perspectiva de incluir [Censo Agropecuário](ftp://ftp.ibge.gov.br/Censos/Censo_Agropecuario_2006/) entre o conjunto de dados disponível para download/leitura?

**Comment by lucasmation** [comment]
A princípio não estava no plano. Debatível.

Ignorância minha: o IBGE divulga microdados (dados individuais (no caso
seria dá propriedade agrícola) desidentificados, sem agregação) ? Se sim,
qual o link?

Em sáb, 14 de jan de 2017 9:02 PM, Tomás Barcellos <notifications@github.com>
escreveu:

**Comment by tomasbarcellos** [comment]
De fato, eles não divulgam. Segue um trecho da resposta do IBGE à minha solicitação de informação no e-SIC:

> Prezado Tomás, O IBGE não divulga os microdados do Censo Agropecuário pois feriria a lei do sigilo estatístico.

Estou fechando a issue
