### ISSUE TITLE
possibles NAs for read_RAIS (and mayb read_CAGED are substrings of {n class}

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#132]
I think the possibile NA values are: 
```
{
{n
{n c
{n cl
{n cla
{n clas
{n class
{n class}
```

**Comment by nicolassoarespinto** [comment]
new output of RAIS is:

`

> str(rais)
Classes ‘data.table’ and 'data.frame':	1832669 obs. of  45 variables:
 $ Bairros SP             : logi  NA NA NA NA NA NA ...
 $ Bairros Fortaleza      : logi  NA NA NA NA NA NA ...
 $ Bairros RJ             : logi  NA NA NA NA NA NA ...
 $ Causa Afastamento 1    : int  99 99 99 99 99 99 99 99 99 99 ...
 $ Causa Afastamento 2    : int  99 99 99 99 99 99 99 99 99 99 ...
 $ Causa Afastamento 3    : int  99 99 99 99 99 99 99 99 99 99 ...
 $ Motivo Desligamento    : int  11 11 11 21 10 11 11 21 31 11 ...
 $ CBO Ocupação 2002      : chr  "717020" "715505" "623310" "514320" ...
 $ CNAE 2.0 Classe        : int  41204 41204 1555 1555 41204 41204 41204 10139 41107 23427 ...
 $ CNAE 95 Classe         : int  45217 45217 1457 1457 45217 45217 45217 15113 70106 26417 ...
 $ Distritos SP           : logi  NA NA NA NA NA NA ...
 $ Vínculo Ativo 31/12    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Faixa Etária           : int  3 7 6 6 4 6 5 4 4 6 ...
 $ Faixa Hora Contrat     : int  6 6 6 6 6 6 6 6 6 6 ...
 $ Faixa Remun Dezem (SM) : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Faixa Remun Média (SM) : int  99 3 4 1 2 3 2 2 0 3 ...
 $ Faixa Tempo Emprego    : int  2 3 6 3 3 3 2 3 4 5 ...
 $ Escolaridade após 2005 : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Qtd Hora Contr         : int  44 44 44 44 44 44 44 44 44 44 ...
 $ Idade                  : int  21 57 41 47 27 47 38 27 26 47 ...
 $ Ind CEI Vinculado      : int  1 1 0 0 0 1 1 0 1 0 ...
 $ Ind Simples            : int  0 0 0 0 0 0 0 0 0 1 ...
 $ Mês Admissão           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Mês Desligamento       : int  2 5 6 1 4 1 1 1 2 7 ...
 $ Mun Trab               : int  530010 530010 530010 530010 530010 530010 530010 530010 530010 530010 ...
 $ Município              : int  530010 530010 530010 530010 530010 530010 530010 530010 530010 530010 ...
 $ Nacionalidade          : int  10 10 10 10 10 10 10 10 10 10 ...
 $ Natureza Jurídica      : int  2062 2062 2062 2062 2062 2062 2062 2062 2062 2062 ...
 $ Ind Portador Defic     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Qtd Dias Afastamento   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Raça Cor               : int  8 8 2 2 2 2 2 8 2 2 ...
 $ Regiões Adm DF         : int  1 1 19 19 3 3 3 1 3 7 ...
 $ Vl Remun Dezembro Nom  : chr  "0000000000,00" "0000000000,00" "0000000000,00" "0000000000,00" ...
 $ Vl Remun Dezembro (SM) : chr  "000000,00" "000000,00" "000000,00" "000000,00" ...
 $ Vl Remun Média Nom     : chr  "0000000000,00" "0000001216,18" "0000001523,46" "0000000723,99" ...
 $ Vl Remun Média (SM)    : chr  "000000,00" "000001,67" "000002,09" "000000,99" ...
 $ CNAE 2.0 Subclasse     : int  4120400 4120400 155502 155502 4120400 4120400 4120400 1013901 4110700 2342702 ...
 $ Sexo Trabalhador       : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Tamanho Estabelecimento: int  1 1 7 7 6 1 1 6 2 4 ...
 $ Tempo Emprego          : chr  "5,1" "7,7" "44,8" "7,3" ...
 $ Tipo Admissão          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Tipo Estab             : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Tipo Estab             : chr  "CNPJ" "CNPJ" "CNPJ" "CNPJ" ...
 $ Tipo Defic             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Tipo Vínculo           : int  10 10 10 10 10 10 10 10 10 10 ...

`
