### ISSUE TITLE
Error with download_sourceData

### ISSUE THREAD

**Issue by vivigui** [lucasmation/microdadosBrasil#133]
Dear Lucas and Nicolas,

I am writing to you because I am getting the following error when trying to download some Brazilian microdata:
```

library(microdadosBrasil)
download_sourceData("CENSO", 2000,unzip = TRUE)
Error in list.files(recursive = TRUE, path = ifelse(is.null(root_path),  : 
  'translateCharUTF8' must be called on a CHARSXP
```

The same happens with download_sourceData("PNAD", 2014, unzip = TRUE)

I am using R version 3.3.3 in Fedora 25. I don't get this error using R version 3.3.2 in Windows 7.

Many thanks in advance.

Kind regards,

Guillermo

**Comment by lucasmation** [comment]
@vivigui : for a quick solution you could do: `download_sourceData("CENSO", 2000,unzip = FALSE)`
then unzip manually, or in a linux shell. 

The problem is that we never really tested the package in a Linux enviroment.

@nicolassoarespinto : this may be a problem with how Linux and Windows handle the strings containing the folder structure. Rafael Dias may have a hint on what can be going on and can help simulate this error in Linux (Ubuntu)

**Comment by vivigui** [comment]
Hi,

Unfortunately I am getting the same error when trying:
download_sourceData("CENSO", 2000, unzip = FALSE)

Guillermo

**Comment by nicolassoarespinto** [comment]
@vivigui 

Please try( on the same directory that you used to download the data): 

`
list.files(recursive = TRUE) 
`
If you get the same error.

Use:

`download_sourceData("CENSO", 2000, unzip = F, replace = T)`

And will probably works.  When `replace = FALSE`  is used(default ) a `list.files` call is done before the download to see if data is not already downloaded.

**Comment by nicolassoarespinto** [comment]
@vivigui If the test above is correct, it may help to run the download function on a clean directory( with nothing inside)

**Comment by vivigui** [comment]
Hi,

Many thanks for these insights. I was able to download the data both in Windows and Linux. I think the best option is to work from a clean directory, as suggested.

Now, I am getting these errors when trying further commands of the Basic Usage section:
d <- read_CENSO('domicilios', 2000)
Error in ifelse(is.null(UF), root_path, paste0(ifelse(is.null(root_path),  : 
  replacement has length zero
In addition: Warning message:
In rep(yes, length.out = length(ans)) :
  'x' is NULL so the result will be NULL
d <- read_CENSO('pessoas', 2000, UF = "DF")
Error in read_CENSO("pessoas", 2000, UF = "DF") : 
  Data not found, check if you provided a valid root_path or stored the data in your current working directory.

When I set the root_path the same error happens. Is this a problem of setting the right working directory? Which one should it be?
d <- read_CENSO('domicilios', 2000, root_path = "S:/USA_data/Brazil_data/r_package_microdados/Microdados/")
Error in read_CENSO("domicilios", 2000, root_path = "S:/USA_data/Brazil_data/r_package_microdados/Microdados/") : 
  Data not found, check if you provided a valid root_path or stored the data in your current working directory.

My aim is to get migration data to create flows matrices. Do you know which text document I should focus on?

Many thanks in advance for everything.

Guillermo

**Comment by nicolassoarespinto** [comment]
@vivigui The first error is probably a bug that I am still checking. 

The last one will work if you don't close the root_path with the last "/". Use:

`d <- read_CENSO('domicilios', 2000, root_path = "S:/USA_data/Brazil_data/r_package_microdados")`

Also, 2000 and 2010 CENSO file structures are very similar, both are stored in a folder named "Microdados", so you may consider put the folder inside a folder like "2000" and then use:

`d <- read_CENSO('domicilios', 2000, root_path = "S:/USA_data/Brazil_data/r_package_microdados/2000")`

Where 'Microdados' folder is inside '2000'

**Comment by vivigui** [comment]
Many thanks for this, it is working now. 

I have also downloaded the PNAD 2014 data and I found this typo:
d <- read_PNAD("pessoas",i = 2014, root_path = "S:/USA_data/Brazil_data/r_package_microdados/PNAD", vars_subset = c("V0302","V4750"))
You have specified the 'root_path' argument, in this case we will assume that data is in the directory specified and it is exactly as it have been downloaded from the source.

[1] "PES2014.txt"
[1] "S:/USA_data/Brazil_data/r_package_microdados/PNAD/2014/Dados_20161116"
character(0)
Error in read_data(dataset = "PNAD", ft, i, root_path = root_path, file = file,  : 
  Data not found. Check if you have unziped the data

The problem is that the name of the folder was Dados_20170323, not Dados_20161116, so if I change manually the name, the previous command works well. Maybe you can correct this typo in your original function.

Guillermo

**Comment by nicolassoarespinto** [comment]
@vivigui IBGE had updated files. I just uploaded a fix for that. The updated included changes in dictionaries,  so if you fixed metadata manually and used the package you probably got wrong results.

**Comment by vivigui** [comment]
Dear Nicolas,

Thanks for the feedback. I have reinstalled the package and when downloading PNAD data for year 2014 it works well, but now the problem is for year 2015. The name of the folder is Dados_20170426 but the function is looking for Dados_20170329. Could this be a new bug?

Kind regards.

Guillermo

**Comment by nicolassoarespinto** [comment]
@vivigui 

They updated the dataset again at April 24 ( just after the last fix). Now it should work( dictionaries changed, there are more variables now)
