### ISSUE TITLE
instalation's problem 

### ISSUE THREAD

**Issue by nat2904** [lucasmation/microdadosBrasil#136]
I am having problem when installing the microdadosBrasil package. Anyone can help me with it? Regards

**Comment by jjesusfilho** [comment]
Me either:
Error: /tmp/RtmpWnWMAI/devtoolsb64302a1064/lucasmation-microdadosBrasil-f58b63e/man/aux_read_fwf.Rd: Sections \title, and \name must exist and be unique in Rd files
* removing ‘/home/adjdsj/R/x86_64-pc-linux-gnu-library/3.3/microdadosBrasil’
Error: Command failed (1)

**Comment by nicolassoarespinto** [comment]
@nat2904 @jjesusfilho 

 I can install the package here;

Could you please paste here the complete output of the error?

**Comment by nicolassoarespinto** [comment]
@nat2904 @jjesusfilho  I think the problem was that 'hms' wasn't listed as a dependency. Please, let me know if it works now.

**Comment by nicolassoarespinto** [comment]
@nat2904 @jjesusfilho  Closing for now as every thing seems to be working, let us know if you still have problems.
