### ISSUE TITLE
Error installation devtools::install_github("lucasmation/microdadosBrasil")

### ISSUE THREAD

**Issue by lucassantosbicalho** [lucasmation/microdadosBrasil#138]
Hi guys, I was looking for something like this for a long time and finally, I found. Congratulations to all workers.

I've tried to install the packages, but in the devtools::install_github("lucasmation/microdadosBrasil") I got this message: Installation failed: Couldn't connect to server.
Then the load of library 'microdadosBrasil' got an error too, "there is no package called 'microdadosBrasil'.

Can I use your package? 
I'm an undergraduate student in Statistics at UFG and it will be very helpful in my monography.

Thanks

**Comment by nicolassoarespinto** [comment]
@lucassantosbicalho 

I think it is a devtools problem  in dealing with firewall/proxy ( see https://github.com/hadley/devtools/issues/877 for reference, there is some suggestions for fix there).

A temporary solution would to download the repo manually:

```
download.file("https://github.com/lucasmation/microdadosBrasil/archive/master.zip", destfile = "master.zip")
unzip("master.zip")
devtools::install_local("microdadosBrasil-master")
```

**Comment by lucassantosbicalho** [comment]
It solved the issue. Thank you!
