### ISSUE TITLE
Variável UF não disponível na PNAD 2014 de Pessoas e Domicílios

### ISSUE THREAD

**Issue by LuanaGV** [lucasmation/microdadosBrasil#143]
O pacote que importa os dados do IBGE, lê os dados em R e os exporta para o Stata não contém a variável UF para a PNAD 2014 de Pessoas e Domicílios. Alguma ajuda com isto pois preciso da variável UF para minha pesquisa. Obrigada.

**Comment by nicolassoarespinto** [comment]
@LuanaGV  Obrigado por avisar, adicionamos a variável ao dicionário. ( a variável tinha sido retirada temporariamente por causa do problema #122, que já foi solucionado)
