### ISSUE TITLE
add support for read_Censo_AgSetor()

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#147]
Censo 2010:
ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_do_Universo/Agregados_por_Setores_Censitarios/

Censo 2000:
ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2000/Dados_do_Universo/Agregado_por_Setores_Censitarios/

Censo 1991:
could not find yet

**Comment by lucasmation** [comment]
@nicolassoarespinto did you already have a code to solve this? (even if not the purest solution). If so, please upload the new functions (or email me if necessary)

**Comment by nicolassoarespinto** [comment]
@lucasmation  Closing for know as we talked before about not implementing this in the package
