### ISSUE TITLE
POF 2002-2003: read_POF search for files of POF 2008

### ISSUE THREAD

**Issue by raphael-gouvea** [lucasmation/microdadosBrasil#148]
After downloading the files for POF 2002, the function read_POF tries to open files named as in POF 2008-2009. For example, running the code below, the system give us the following error message after read_POF:
Error in read_data(dataset = "POF", ft = ft, i = i, root_path = root_path,  : 
  ft (file type) must be one of these: T_CADERNETA_DESPESA_S, T_CONDICOES_DE_VIDA_S, T_DESPESA_12MESES_S, T_DESPESA_90DIAS_S, T_DESPESA_INDIVIDUAL_S, T_DESPESAS_VEICULO_S, T_DOMICILIO_S, T_INVENTARIO_S, T_MORADOR_IMPUT_S, T_MORADOR_S, T_OUTRAS_DESP_S, T_OUTROS_RECI_S, T_RENDIMENTOS_S, T_SERVICO_DOMS_S. See table of valid file types for each period at "http://www.github.com/lucasmation/microdadosBrasil

If you check the downloaded files, the file name for POF 2002-2003 is "T_DESPESA_12MESES.TXT". I also tried to rename it by hand and, then, use read_POF with ft="T_DESPESA_12MESES_S", but it returns the same error message.

library(microdadosBrasil)
#folder path
pof.path = "/home/raphael/Desktop/MicroBrasil"
#download
download_sourceData("POF", 2002, T, root_path =  pof.path)
#read
pof_desp<- read_POF(ft = "T_DESPESA_12MESES", 2002, root_path = pof.path)
#show downloaded files
list.files(paste0(pof.path,"/Dados"))

**Comment by nicolassoarespinto** [comment]
@raphael-gouvea 

Thanks a lot for this input, we found out that POF 2002 was incomplete in the package, there were not even dictionaries. I used the opportunity to also change the `file_type` the syntax and set for the download function to download the whole folder, including documentation. 

So, please: 

- Download the data again, to download the whole folder and also fix any filename that you may have changed. 
- Now the import function will use the filetypes below:
```

get_available_filetypes("POF", 2002)
 [1] "caderneta_despesa"  "condicoes_de_vida"  "despesa_12meses"    "despesa_90dias"    
 [5] "despesa_individual" "despesa_veiculo"    "domicilio"          "inventario"        
 [9] "morador"            "outras_despesas"    "outros_rendimentos" "rendimentos"       
[13] "servico_domestico"  "despesa_esp"       

get_available_filetypes("POF", 2008)
 [1] "aluguel_estimado"   "caderneta_despesa"  "condicoes_de_vida"  "consumo"           
 [5] "despesa_12meses"    "despesa_90dias"     "despesa_individual" "despesa_veiculo"   
 [9] "domicilio"          "inventario"         "morador_imput"      "morador"           
[13] "outras_despesas"    "outros_rendimentos" "rendimentos"        "servico_domestico" 
```


It seems that everything is working now, but I didn't have the time to check each dataset manually ( the dictionaries were created from SAS IBGE dictionaries), so any feedback you have on this will be very helpful.

**Comment by nicolassoarespinto** [comment]
@raphael-gouvea  I also used the same  "friendly" file type names that were used in the comments of the IBGE programs, if you have experience with the dataset we would welcome any suggestion for a more descriptive name.

**Comment by raphael-gouvea** [comment]
Thanks. If I find anything else I'll let you guys know.

**Comment by raphael-gouvea** [comment]
I don't know what is the standard you are adopting for the package, but it would be if the variables were labeled. Taking a look in the SAS dictionary that should not be hard to do since the labels are already in the dictionary.

**Comment by lucasmation** [comment]
As far as I know, labeling vars in R is not trivial. How do you suggest we
do it?


When I import an spss file or SAS file to R using the haven package, the
columns come as  "atomic" vectors, which contain variable names and value
labels. But I find these var types a bit weird and error prone (although
recently I used a SPSS Census file, converted it to data table and used it
normally without error)

2017-08-08 11:20 GMT-03:00 Raphael Gouvea <notifications@github.com>:

**Comment by raphael-gouvea** [comment]
I haven't had any problems with atomic variables. For labeling, I've been using the package labelled. See the example below. I'm using dicionariosIBGE only to get the labels. You basically pass a list containing var names and labels into the var_label function from labelled package. It automatically converts the variables in atomic though.

library(microdadosBrasil)
library(tidyverse)
library(labelled)
library(dicionariosIBGE)

#local onde serão baixados os dados
pof.path = "/home/raphael/Dropbox/2017/LargeDevaluations/POF2002_t"

#download
download_sourceData("POF", 2002, T, root_path =  pof.path)

#Read
pof_desp<- read_POF(ft = "despesa_90dias", 2002, root_path = pof.path)

#Label
dic<-data(dicPOF2002.2003)
labels<-as.character(dic13pof2002.2003$desc)
pof_desp_names<-names(pof_desp)
pof_desp_labels<-setNames(labels,pof_desp_names)
var_label(pof_desp) <- as.list(pof_desp_labels)
str(pof_desp)

**Comment by raphael-gouvea** [comment]
Regarding the updates on read_POF. I think the behavior when replace=F changed. If I run download_sourceData("POF", 2002, T, root_path = pof.path) twice it will download the data twice. If I remember right, in the previous version in the second time it would return a message saying that the files were already downloaded. In sum, it seems that the default for replace is now T.

**Comment by raphael-gouvea** [comment]
Sorry, just realized there were two mistakes in my previous code. I mess up with the order of the var names and labels and was using a wrong dictionary. Below, it is the correct code.

#Read
pof_desp<- read_POF(ft = "despesa_90dias", 2002, root_path = pof.path)
is.data.frame(pof_desp)

#Label
dic<-data(dicPOF2002.2003)
labels<-as.character(dic5pof2002.2003$desc)
pof_desp_names<-as.character(dic5pof2002.2003$cod)
pof_desp_labels<-setNames(labels,pof_desp_names)
var_label(pof_desp) <- as.list(pof_desp_labels)
str(pof_desp)

**Comment by raphael-gouvea** [comment]
there is an issue with the read_POF function. I have not checked for 2008, but for 2002 the function is searching for wrong file names (e.g. T_DESPESA_VEICULO.TXT when the file name is T_DESPESAS_VEICULO.TXT). 
# Problem
library(microdadosBrasil)
download_sourceData("POF", 2002, T, root_path = "input/",replace=T)
file_types <- get_available_filetypes("POF",2002)
for(i in file_types){
  assign(i,read_POF(ft=i,2002,root_path="input/"))
}
# Solution
# Adjust file names (bug in microdadosBrasil)
file.rename(from="input/Microdados/Dados/T_DESPESA_VEICULO.TXT",
            to="input/Microdados/Dados/T_DESPESAS_VEICULO.TXT")
file.rename(from="input/Microdados/Dados/T_OUTRAS_DESPESAS.TXT",
            to="input/Microdados/Dados/T_OUTRAS_DESP.TXT")
file.rename(from="input/Microdados/Dados/T_RENDIMENTOS1.txt",
            to="input/Microdados/Dados/T_RENDIMENTOS.txt")
for(i in file_types){
  assign(i,read_POF(ft=i,2002,root_path="input/"))
}
