### ISSUE TITLE
add RAIS

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#15]
ftp://ftp.mtps.gov.br/pdet/microdados/RAIS/2014/

**Comment by lucasmation** [comment]
ftp://ftp.mtps.gov.br/pdet/microdados/Comunicado_microdados.pdf

**Comment by nicolassoarespinto** [comment]
done. Couldn't add the download functionality due to the structure of the links.

**Comment by lucasmation** [comment]
they are in an FTP server. It actually should be easier to download

http://stackoverflow.com/questions/33534845/download-large-zip-file-from-ftp-server-with-r

http://stackoverflow.com/questions/33534845/download-large-zip-file-from-ftp-server-with-r

download from FTP with R

**Comment by lucasmation** [comment]
done
