### ISSUE TITLE
Leitura dos microdados POF

### ISSUE THREAD

**Issue by lucianomoura90** [lucasmation/microdadosBrasil#157]
Quando vou ler os dados da POF, o programa não me retorna os dados prontos, preciso usar o 7.zip, para extrair outro zip dentro da pasta dados, para assim pode usar os dados. Sendo que a ideia do microdados e fornecer os dados prontos para leitura.

**Comment by nicolassoarespinto** [comment]
@lucianomoura90  Adicionei uma solução parcial para isso recentemente. Basta instalar o pacote [archive](https://github.com/jimhester/archive) e utilizar a função `unzip_all_7z`. Como o `archive` ainda não está no CRAN e não há uma solução nativa para unzip de arquivos `.7z` e `.rar` em R, não colocamos o unzip dentro da própria função de download. O código completo seria algo assim:

```
install_gihub("jimhester/archive")
library(archive)
library(microdadosBrasil)

pof.path = ".../Datasets/POF"
download_sourceData("POF", i = 2008, root_path = pof.path, unzip = T)
unzip_all_7z(pof.path)

pof <- read_POF(ft = "quadro_desejado_aqui", i = 2008, root_path = pof.path)


```

Cuidado em onde armazena os dados( sugeriria não colocar em pastas com muitos outros arquivos, como Documentos) pois a função fará unzip de todos os arquivos dentro da pasta recursivamente.
