### ISSUE TITLE
Error in download_souceData

### ISSUE THREAD

**Issue by danielcastelan** [lucasmation/microdadosBrasil#166]
Pessoal,
tentando baixar os dados do Censo no Ubuntu-Linux, depois de ter instalado o pacote, me deparo com uma mensagem de erro.

O comando usado foi:
`download_sourceData("CENSO", 2000, unzip=T)`

E a mensagem de erro:

> Error in download_sourceData("CENSO", 2010, unzip = T) : 
  Invalid dataset. Must be one of the following: x86, x86, x86, x86, x86, x86, x86, x86, x86, x86, x86

Alguma ajuda?

**Comment by lucasmation** [comment]
Este é o mesmo erro de #161

This is a duplicate of #161

Estamos trabalhando para solucionar isso o quanto antes possível

Em qui, 29 de mar de 2018 08:38, danielcastelan <notifications@github.com>
escreveu:

**Comment by lucasmation** [comment]
@danielcastelan , 

acredito que o erro tenha sido corrigido (no issue #164). Poderia testar novamente e colocar o resultado aqui?

**Comment by danielcastelan** [comment]
Lucas, estou meio enrolado, mas vou testar nos próximos dias. Aproveito pra
agradecer muito e parabenizar pelo excelente trabalho que presta a toda a
sociedade. Analisar os dados é passo fundamental pra qualquer política
pública.

Um forte abraço,

Daniel R Castelan
Universidade Federal de Santa Catarina

2018-04-03 7:44 GMT-03:00 lucasmation <notifications@github.com>:

**Comment by danielcastelan** [comment]
@lucasmation,

Resolvido!
Atualizei os pacotes e agora consigo baixar. Os comandos foram os seguintes, conforme indicado no issue #164 :

`install.packages("devtools")`
`install.packages("stringi")`
`devtools::install_github("lucasmation/microdadosBrasil")`
`library("microdadosBrasil")`

`download_sourceData("CENSO", 2000, unzip=T)`

Muito obrigado e parabéns pelo trabalho!
