### ISSUE TITLE
Add Continuous PNAD

### ISSUE THREAD

**Issue by tamaravaz** [lucasmation/microdadosBrasil#171]
Tentei utilizar o pacote para ler as Pnads contínuas anuais e nao há suporte. 

Poderiam dar suporte a isso? 

local de microdados:
[Site estatísticas IBGE](https://downloads.ibge.gov.br/downloads_estatisticas.htm) ->trabalho_e_Rendimento -> Pesquisa_Nacional_por_Amostra_de_Domicilios_continua -> Anual -> Microdados

**Comment by lucasmation** [comment]
@monteirogustavo , como está esta implementação? Precisamos disso com certa urgência

**Comment by tamaravaz** [comment]
@monteirogustavo, 

diferença entre a 1ª e 5º visita [aqui](https://www.ibge.gov.br/estatisticas-novoportal/sociais/trabalho/17270-pnad-continua.html?=&t=o-que-e). O que queremos é a primeira visita mesmo.

```
Temas e tópicos pesquisados ao longo do ano em determinada visita:
Habitação (1a visita);
Características gerais dos moradores (1a visita);
Informações adicionais da força de trabalho (1a visita);
Outras formas de trabalho (afazeres domésticos, cuidados de pessoas, produção para o próprio consumo e trabalho voluntário) (5a visita);
Trabalho de crianças e adolescentes (5a visita); e
Rendimentos de outras fontes (1a e 5a visitas).
```

**Comment by lucasmation** [comment]
se não me engano o identificador de perído das Pnad Contínuas era:  `2018,1q` (2q, 3q, 4q)
Acho que para a anual pode ser: `2018,anual.1v` e `2018,anual.5v`
Cada uma destas seria uma linha em: https://github.com/lucasmation/microdadosBrasil/blob/master/inst/extdata/PnadContinua_files_metadata_harmonization.csv
