### ISSUE TITLE
PNADs 1976-1999

### ISSUE THREAD

**Issue by antrologos** [lucasmation/microdadosBrasil#174]
Olá Lucas, 

Seria possível adicionar dicionários para a leitura das PNADs de 1976 a 1999 (que se encontram de fato no FTP do IBGE) e dos Censos de 1980 e 1991 (esses, infelizmente não disponíveis on-line)?

**Comment by lucasmation** [comment]
@antrologos, passei a parte dos Censos para outra issue (#175) para não misturar. 

Nos na verdade já tinhamos incluido esta PNADs, só tinhamos esquecido de mudar o leiame para avisar disso.

**Comment by lucasmation** [comment]
@antrologos , esta aí

```
download_sourceData("PNAD", 1976, unzip = T)
d  <- read_PNAD("domicilios", 1976)
```

se necessário, reabra o issue

**Comment by antrologos** [comment]
Obrigado. Testei aqui e funcionou
