### ISSUE TITLE
add get_import_dictionary function

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#24]
didn´t we use to have a get_import_dictionary() function?

it should be added to dictionary_functions.R

**Comment by nicolassoarespinto** [comment]
I think you renamed the function on [this comit](https://github.com/lucasmation/microdadosBrasil/commit/cbd5788628dfa977794c9ed1789e3ec28790345c)

**Comment by lucasmation** [comment]
no, 

that as the "import" dicionary function. 

get_import_dictionary would go into the list of dicionaries for a dataset-subdataset-year and return that data-frame

just a little function: 
get_import(dataset= 'PNAD', subdataset ='domcilios',year==2002)

that returns the correct dictionary, without the person needing to know the way we store that internally (as lists)

**Comment by nicolassoarespinto** [comment]
Completed in #25
