### ISSUE TITLE
Encoding problem in unzip()

### ISSUE THREAD

**Issue by nicolassoarespinto** [lucasmation/microdadosBrasil#27]
Some filenames contain latin characters. This is a problem when extracting files using the unzip() function, apparently, there is no builtin option to deal with this characteres. Example: in dataset Censo da Educação Superior, after the extraction of year 2011, the data folder became "Microdados  Educa‡Æo Superior 2011" 
Until this problem is solved, metadata for Censo da Educação Superior contains corrupted filenames, so years 2005,2006,2007 and 2011 can only be read if download and unzip was made by the function download_sourceData().

**Comment by lucasmation** [comment]
This may be a problem with the encoding of our .csv files. Check if making
the csv files utf-8 instead of Latin1 solves this

Em Qua, 22 de jun de 2016 4:11 PM, nicolassoarespinto <
notifications@github.com> escreveu:

**Comment by nicolassoarespinto** [comment]
The problem is not in .csv files, they can store either the corrupted filenames or the non corrupted ones.  I purposely chose (while we can't solve the problem) to store the corrupted filenames in them, so there are no inconsistencies between download_sourceData() and read_dataset().
The problem is in download or unzip.

**Comment by nicolassoarespinto** [comment]
Just posted in stackoverflow: http://stackoverflow.com/questions/38082887/how-to-deal-with-latin-characteres-in-unzip

**Comment by nicolassoarespinto** [comment]
Additional information: the documentation of the function unzip() explicit says that:

-  The internal implementation don't support unicode characters, for that you need to install an external tool ( like 7zip)

- It can have problems to deal with big files ( says >4GB), i think this can be related with the issue #4 

Maybe we should drop this functionality and just give a warning about the need to decompress the files manually. What do you think @lucasmation ?

**Comment by lucasmation** [comment]
does this only happen in Censo da Educação Superior?

**Comment by nicolassoarespinto** [comment]
Closing for now, don't think we can solve this.
