### ISSUE TITLE
read_CensoEscolar( ft = "escola", i = 1996) doesn't work

### ISSUE THREAD

**Issue by nicolassoarespinto** [lucasmation/microdadosBrasil#28]
It loads until 99% then R stops. Was tested on server and local computer .

**Comment by lucasmation** [comment]
did you try debugging? where does it hang? The R server was upgraded to 3.3 recently. What version is R in your PC?

**Comment by lucasmation** [comment]
did the function used to work before? or was it the first test for this dataset-subdataset-year?

**Comment by nicolassoarespinto** [comment]
It was the first test and the error is in read_fwf(). I checked metadata and dictionaries and there is no problem with them. 
My R version is 3.2.3.

**Comment by lucasmation** [comment]
what was the error message? Please provide reproducible example base only on read_fwf, the data file and the dictionary

**Comment by lucasmation** [comment]
do the other years work?

**Comment by nicolassoarespinto** [comment]
All other years work.  

I just noted that the problem is just a matter of memory( weird that this happens even on the server, but the dataset is really big), after reloading R i managed to load the dataset. 
Just in case, here is a reproducible example (note that function read_fwf() is internal to the package and you need to source it manually before the test):


```
library(readr)

dic<- get_dictionary("CensoEscolar",1996,"escola")

f<- "C:/.../DADOS_CENSO96.txt"


d<- f %>% read_fwf(fwf_positions(start=dic$int_pos,end=dic$fin_pos,col_names=dic$var_name),
         col_types=paste(dic$col_type,collapse =''))
```

**Comment by nicolassoarespinto** [comment]
@lucasmation I just confirmed that the problem is not at read_fwf at all, solved and it is working for all years now.
