### ISSUE TITLE
Update Censo Escolar for changes (csv to txt) introduced by INEP recently

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#33]

**Comment by lucasmation** [comment]
please also check if the municipal codes were corrected by INEP on the new Censo Escolar data. The dictionaries claimed codmun was 12 digits, when, in fact,  it should be 7 digits

**Comment by nicolassoarespinto** [comment]
All dictionaries until 2006 show CODMUN with 12 digits. Checked both SAS, SPSS and our translations.

**Comment by nicolassoarespinto** [comment]
Completed txt-csv change in the last pull request
