### ISSUE TITLE
change read_PNADContinua to read_PNADcontinua (check internals)

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#34]
I changed the function name: 

read_PNADContinua
to 
read_PNADcontinua

I only changed the function name and the README.
please check if other internal commands (dictionary, metadata csv) also need to change accordingly. And test files too.

**Comment by nicolassoarespinto** [comment]
done

**Comment by lucasmation** [comment]
I mean, I think you have to update the internals, so dicionary and metadata files are consistent with the function name

PNADContinua_dics shold be PNADcontinua_dics  , etc... 

read_PNADcontinua<- function(ft,i,root_path=NULL){

  metadata <-  read_metadata('PnadContinua')

  data("PNADContinua_dics")



  data<-read_data(ft, i, metadata, dic = PNADContinua_dics,root_path =  root_path)

  return(data)
}
