### ISSUE TITLE
add README_POR file

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#40]
It would be nice to add a README_PT file, to have the documentation in Portuguese. 

We need to check how to do that with devetools

Perhaps one solution is to create a function similar to use_readme_rmd (see code bellow), but changing every README for README_PT

please check if this could work

use_readme_rmd
function (pkg = ".") 
{
    pkg <- as.package(pkg)
    use_template("README.Rmd", ignore = TRUE, open = TRUE, pkg = pkg)
    use_build_ignore("^README-.*\\.png$", escape = FALSE, pkg = pkg)
    if (uses_git(pkg$path) && !file.exists(pkg$path, ".git", 
        "hooks", "pre-commit")) {
        message("* Adding pre-commit hook")
        use_git_hook("pre-commit", render_template("readme-rmd-pre-commit.sh"), 
            pkg = pkg)
    }
    invisible(TRUE)
}

**Comment by nicolassoarespinto** [comment]
I started debug mode and changed the internal variable `save_as` from `README.rmd` to `README_PT.rmd` and it worked. The devtools functions use some functions that are not exported to the package, so i couldn't define a function that creates the files. Don't think we will need to create the templates again, so it is not a problem.

**Comment by nicolassoarespinto** [comment]
I also did it for `README_PT.md`
