### ISSUE TITLE
new syntax for period (i) when data is quarterly or monthly

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#54]
yearly data, will accept year in numeric (2010) or string ( '2010' ) formats. 

quartely data  and montly data have to be strings. and be explicit: 

'2014-1q'   (1st quarter)

'2015-1m' (jan)

**Comment by nicolassoarespinto** [comment]
Now CAGED and PME use the pattern: '2014-1m' and PNADcontinua the pattern '2015-1q'
