### ISSUE TITLE
ftp data should download to a dataset-year specific folder

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#62]

**Comment by nicolassoarespinto** [comment]
For now the download is done in one folder created with the name of the ftp folder. Now, all datasets with ftp sources covered by the package happens to be in a folder with the year as the name, so for now it is working. Let me know if this is not the appropriate behavior and we should ignore the ftp folder name and use directly the year.

Example:  [PNAD 2014](ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_anual/microdados/2014/) is downloaded to a folder named "2014" , and
