### ISSUE TITLE
Censo Escolar de 2006 lê dados de 2005?

### ISSUE THREAD

**Issue by palmaresk8** [lucasmation/microdadosBrasil#66]
No arquivo CensoEscolar_files_metadata_harmonization.csv, no ano de 2006, a coluna ft_escola_em_e_emprof está com valor INPUT_SAS_EM22.sas&EM22_2005.TXT, ou seja, tenta fazer a leitura do dado de 2005 (se eu entendi direito). Isso se repete nas colunas ft_escola_educprof.

**Comment by lucasmation** [comment]
must be a bug. @nicolassoarespinto can you check and fix this?

**Comment by nicolassoarespinto** [comment]
@palmaresk8 @lucasmation corrigido no #67
