### ISSUE TITLE
Source_file_mark=TRUE

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#82]
@nicolassoarespinto , 

what do you think of adding a new parameter "Source_file_mark=TRUE" to the import functions?
This would add a column containing the name of the file where the observation was downloaded from. 
This is relevant for datasets that come spread across multiple files, and our import functions gather the data into a single data.table. Afterward, if someone sees something weird if an observation, it is not clear from which file it came from. So the package would do something like this: 

Source_file_mark=TRUE  >> add column Source_file

this would contain, for 

read_SISOB("obitos", c(200103,200104) ) -> d

d would contain

Source_file
200103.txt
200103.txt
...
...
200304.txt
...

The default would be Source_file_mark=TRUE, but the person could opt out, with Source_file_mark=FALSE

let me know wat you think and I can implement that

**Comment by nicolassoarespinto** [comment]
@lucasmation it seems like a very good idea. But maybe the default should be `Souce_file_mark = FALSE` , as most datasets aren't spreads like that. In this way we don't need to add one more step/piece of information for the simplest user.
