### ISSUE TITLE
Can´t download CENSUS data

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#85]
I could not download Census data. Did we break something? 

I tryed: 

> download_sourceData("CENSO", 2000, unzip = T)
> Error in download_sourceData("CENSO", 2000, unzip = T) : 
>   Invalid dataset. Must be one of the following: CadUnico, CAGED, CensoEducacaoSuperior, CensoEscolar, CensoIBGE, PME, PNAD, PNADContinua, POF, RAIS, SISOB
> 
> download_sourceData("CENSO", 2010, unzip = T)
> Error in download_sourceData("CENSO", 2010, unzip = T) : 
>   Invalid dataset. Must be one of the following: CadUnico, CAGED, CensoEducacaoSuperior, CensoEscolar, CensoIBGE, PME, PNAD, PNADContinua, POF, RAIS, SISOB

This code above was working before (it is the first example in the package README file....)

Also the error message indicates that microdadosBrasil expects "CensoIBGE"
I tryed with that but it also did not work

> download_sourceData("CensoIBGE", 2010, unzip = T)
> Error in download_sourceData("CensoIBGE", 2010, unzip = T) : 
>   Can't download dataset, there are no information about the source

Then I tryed repeating the code above, just changing to 2000, but got a weird message: 

> download_sourceData("CensoIBGE", 2000, unzip = T)
> Error in download_sourceData("CensoIBGE", 2000, unzip = T) : 
>   This data was already downloaded.(check:
> ./testing_integen_mobility_within_young_adults_living_with_parents_Brazil_Census.R)
> If you want to overwrite the previous files add replace=T to the function call.

THe check if the data already exist is wrong. I think it is currently just checking if there is any file on the folder (see message above). 

@nicolassoarespinto , can you take a look?

**Comment by lucasmation** [comment]
These variations also do not work

> download_sourceData("CensoIBGE", 2000, unzip = T, replace=T)
Error in download_sourceData("CensoIBGE", 2000, unzip = T, replace = T) : 
  Can't download dataset, there are no information about the source
> download_sourceData("Censo", 2000, unzip = T, replace=T)
Error in download_sourceData("Censo", 2000, unzip = T, replace = T) : 
  Invalid dataset. Must be one of the following: CadUnico, CAGED, CensoEducacaoSuperior, CensoEscolar, CensoIBGE, PME, PNAD, PNADContinua, POF, RAIS, SISOB
> download_sourceData("CENSO", 2000, unzip = T, replace=T)
Error in download_sourceData("CENSO", 2000, unzip = T, replace = T) : 
  Invalid dataset. Must be one of the following: CadUnico, CAGED, CensoEducacaoSuperior, CensoEscolar, CensoIBGE, PME, PNAD, PNADContinua, POF, RAIS, SISOB
>

**Comment by nicolassoarespinto** [comment]
@lucasmation I checked the file, and it seems like we have [never committed download source to Censo metadata](https://github.com/lucasmation/microdadosBrasil/commits/master/inst/extdata/CensoIBGE_files_metadata_harmonization.csv) . Really strange beacause I also remember of this example. Working on that.

**Comment by nicolassoarespinto** [comment]
@lucasmation should we keep "CensoIBGE" or "CENSO" as the name?

**Comment by nicolassoarespinto** [comment]
@lucasmation maybe "CensoDemografico"

**Comment by lucasmation** [comment]
CENSO

Em qua, 19 de out de 2016 12:54 PM, nicolassoarespinto <
notifications@github.com> escreveu:

**Comment by lucasmation** [comment]
> download_sourceData("CENSO", 2000, unzip = T)
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to ftp.ibge.gov.br port 21: Timed out

Error, maybe problems at the source. 

However I still get the error: 

> download_sourceData("CENSO", 2010, unzip = T)
Error in download_sourceData("CENSO", 2010, unzip = T) : 
  Can't download dataset, there are no information about the source

din´t we include Censo 2010 before?
