### ISSUE TITLE
Reading a subset of variables

### ISSUE THREAD

**Issue by rafapereirabr** [lucasmation/microdadosBrasil#94]
Hi guys,

I was wondering if you could include an argument to the `read_DATA` function that specifies the variables that should be read. This argument would be extremely useful for reasons of time efficiency and/or memory limits. Most of the times, we don't need to read the entire census data set, but only a subset of its columns.

As you know, this is quite straightforward with `readr`. Here is what I usually do it:

```
# load data dictionary as a data.table
  dic_dom <- get_import_dictionary("CENSO", 2000, "domicilios") %>% setDT()

# Select a subset of variables which will be read from .txt files
  myvaribles_dom <- c("V0102", "V0103", "V0104", "V0300", "V0400", "V1007")
  dic_dom <- dic_dom[var_name %in% myvariblesDOM] # filter documentation


# read selected variables
  read_fwf( datafile,
            fwf_positions(start = dic_dom[,int_pos], 
                          end = dic_dom[,fin_pos], 
                          col_names = dic_dom[,var_name] ),
            progress = interactive())
```

**Comment by nicolassoarespinto** [comment]
@rafapereirabr  @lucasmation 

Great idea! Just implemented in #95 . Do you know if the solution you use works for big datasets? It seems to me that internally `readr` reads the entire dataset and then it chooses only the selected columns. I couldn't load `Censo Escolar` with this, but it works fine with smaller datasets, like `PNAD`.

Also, we still need to create metadata for the variables of the datasets that don't use dictionaries, so for know we can't test that the subset of variables provided in `read_data` is valid. With this said, i think we gonna keep this on the branch *subset-variables* for a while.

You can install this version with:

`install_github("lucasmation/microdadosBrasil", branch = "subset-variables")`

**Comment by rafapereirabr** [comment]
@nicolassoarespinto Thanks for implementing the idea !

I'm not entirely sure about the inner workings of `readr` when it comes to memory allocation, although it seems to me it only reads the requested columns. I can say I've been using this `read_fwf{readr}` to read a subset of variables in Pnad and Censo Demografico 2000 and 2010 and it works quite well and saves me a lot of time.

**Comment by lucasmation** [comment]
@rafapereirabr 
great idea

@nicolassoarespinto :
Nice, but I think we should do this minor change:

for the fwf part:
I think it would be easier and clearer if instead of changing the heart of read_data and its inner functions we just subset the import dictionary for that dataset-filetype-period, to keep only the rows associated with the desired variables (ask me in person today if necessary).

for the .csv part: fine as in your commit. 

Also, please test if this works for reading a var_subset of a large dataset that with all vars would not fit into memory (CENSO in a desktop PC for instance). 
Please make this test for both fwf and csv files

**Comment by rafapereirabr** [comment]
@nicolassoarespinto I have tested the new functions and it works really well ! I hope you can merge this change to the master branch.

thanks so much  and well done for such a great work you guys are doing !
