### ISSUE TITLE
Create dictionaries for non fwf datasets

### ISSUE THREAD

**Issue by nicolassoarespinto** [lucasmation/microdadosBrasil#96]
We could use it to optimize column classes and in #95 and #94 , to keep track of available variables in each dataset.

**Comment by lucasmation** [comment]
Yes. I am a little worried this means more stuff for us to keep track of, no?

**Comment by nicolassoarespinto** [comment]
@lucasmation Good point. Will try to close others things first, but I still think it's worth it.

**Comment by nicolassoarespinto** [comment]
Wont be implemented for now
