### ISSUE TITLE
import dictionaries should also be CSV files (as with the metadata files)

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#97]
existential question: why don't we have the import dictionaries as .csv files, as we do for the metadata files?

I think we should do that. That way every metadata is on the same file type, and all of if can be revised by non-programmers if necessary. 

@nicolassoarespinto: do you see any problem with this?

**Comment by nicolassoarespinto** [comment]
@lucasmation really good point. I was already feeling that the list structure that we were using was too complicated.  And as you said, there is no point in keeping this as `data.frames` . Working on that.

**Comment by lucasmation** [comment]
maybe we could have  a structure like:

dataset_folder
- metadata_daset.cvs
- variable_harmonization_dataset_filetype.csv
- categories_harmonization_dataset_filetype.csv
- dicionary_foler
-- import_dicionary_dataset_filetype_period1.csv
-- import_dicionary_dataset_filetype_period2.csv
-- import_dicionary_dataset2_filetype_period1.csv

2016-11-16 15:28 GMT-02:00 nicolassoarespinto <notifications@github.com>:

**Comment by lucasmation** [comment]
Nice, 
but lets run our tests on that

**Comment by lucasmation** [comment]
Also, please extend this to microdadosBrasil-RA
